# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: indexer
networks:
- id: 43114
  start_block: 0
  contracts:
  - name: OrganizationNFTCertificate
    address:
    - 0x0B101803e331184b97b1333298437a1183074fb4
    handler: src/EventHandlers.ts
    events:
    - event: Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)
    - event: ApprovalForAll(address indexed owner, address indexed operator, bool approved)
    - event: BatchMetadataUpdate(uint256 _fromTokenId, uint256 _toTokenId)
    - event: CertificateMinted(address organization, address recipient, uint256 tokenId, string tokenURI)
    - event: MetadataUpdate(uint256 _tokenId)
    - event: OrganizationRegistered(address organization, string logoUrl, string brandColor)
    - event: RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)
    - event: RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)
    - event: RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)
    - event: Transfer(address indexed from, address indexed to, uint256 indexed tokenId)
unordered_multichain_mode: true
preload_handlers: true
